Models/EventsFolder/Event.cs
using DiplomService.Services;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace DiplomService.Models
{
    public class Event
    {
        [Key]
        public int Id { get; set; }


        public byte[]? PriviewImage { get; set; } = null;

        [MaxLength(40)]
        [Display(Name = "Название*")]
        public string Name { get; set; } = "";

        [Display(Name = "Описание")]
        public string? Description { get; set; }

        [Display(Name = "Дата начала*")]
        public DateTime DateOfStart { get; set; }

        [Display(Name = "Дата окончания")]
        public DateTime? DateOfEnd { get; set; }

        [Display(Name = "Является ли событие публичным*")]
        public bool PublicEvent { get; set; } = true;

        [Required]
        public bool ReadyToShow { get; set; } = false;

        [Required]
        public bool DivisionsExist { get; set; } = true;

        [JsonIgnore]
        public virtual List<Organization> Organizations { get; set; } = new();
        [JsonIgnore]
        public virtual List<Measure> Measures { get; set; } = new();
        [JsonIgnore]
        public virtual List<Division> Divisions { get; set; } = new();
        [JsonIgnore]
        public virtual List<News> News { get; set; } = new();
        [JsonIgnore]
        public virtual List<EventApplication>? EventApplications { get; set; }

        [NotMapped]
        public string? MimeType { get { return ImageWorker.GetImageMimeType(PriviewImage); } }

        [NotMapped]
        public int EventMembers
        {
            get
            {
                return Divisions.SelectMany(d => d.DivisionMembers).Select(x=>x.User).Distinct().Count();
            }
        }
    }
}

ViewModels/News/NewsListViewModel.cs
namespace DiplomService.ViewModels.News
{
    public class NewsListViewModel
    {
        public int? EventId { get; set; }
        public string? EventName { get; set; }
        public List<Models.News> News { get; set; } = new List<Models.News>();
    }
}

Controllers/ApiContollers/EventsController.cs
using DiplomService.Database;
using DiplomService.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DiplomService.Controllers.ApiContollers
{
    [Route("api/[controller]")]
    [ApiController]
    [Authorize]
    public class EventsController : ControllerBase
    {
        private readonly ApplicationContext _context;
        private readonly UserManager<User> _userManager;

        public EventsController(ApplicationContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: api/Events
        [HttpGet("GetEvents")]
        public async Task<ActionResult<IEnumerable<Event>>> GetEvents()
        {
            if (_context.Events == null)
            {
                return NotFound();
            }
            return await _context.Events.Where(x => x.ReadyToShow && x.PublicEvent).ToListAsync();
        }

        [HttpGet("GetEventsForUser")]
        public async Task<ActionResult<IEnumerable<Event>>> GetEventsForUser()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound();
            }
            else
            {
                var events = _context.Users
                    .Where(mu => mu == user)
                    .SelectMany(mu => mu.UserDivisions)
                    .Select(du => du.Division.Event)
                    .Where(e => e.ReadyToShow && (e.DateOfEnd == null ||e.DateOfEnd>DateTime.UtcNow))
                    .Distinct()
                    .ToList();
                return Ok(events);
            }
        }

        [HttpGet("GetEvent/{id}")]
        public async Task<ActionResult<Event>> GetEvent(int id)
        {
            
            var user = await _userManager.GetUserAsync(User);
            if (user is null)
                return NotFound();
            if (_context.Events is null)
                return NotFound();
            var @event = await _context.Events.FirstOrDefaultAsync(x=>x.Id == id);
            if (@event is null)
                return NotFound();
            if (@event.DivisionsExist)
                @event.Divisions = @event.Divisions.Where(div => div.DivisionMembers.Any(dm => dm.UserId == user.Id)).ToList();
            return @event;
        }
    }
}

Controllers/ApiContollers/NewsController.cs
using DiplomService.Database;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DiplomService.Controllers.ApiContollers
{
    [Route("api/[controller]")]
    [ApiController]
    public class NewsController(ApplicationContext context) : ControllerBase
    {
        private readonly ApplicationContext _context = context;

        [HttpGet("GetEventNews/{eventId}")]
        public async Task<IActionResult> GetEventNews(int eventId)
        {
            var @event = await _context.Events.FirstOrDefaultAsync(x => x.Id == eventId);
            if (@event is null)
                return NotFound();

            return Ok(@event.News);
        }

        [HttpGet("GetNews/{id}")]
        public async Task<IActionResult> GetNews(int id)
        {
            var news = await _context.News.FirstOrDefaultAsync(x => x.Id == id);
            if (news is null) return NotFound();
            return Ok(news);
        }
    }
}

Controllers/ServiceControllers/NewsController.cs
using DiplomService.Database;
using DiplomService.Models;
using DiplomService.ViewModels.News;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DiplomService.Controllers
{
    public class NewsController : Controller
    {
        private readonly ApplicationContext _context;
        private readonly UserManager<User> _userManager;

        public NewsController(ApplicationContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(int? id)
        {
            var model = new NewsListViewModel();

            if (id is null)
            {
                model.News = await _context.News.Where(x => x.Event.PublicEvent).OrderByDescending(x => x.DateTime).ToListAsync();
            }
            else
            {
                var @event = await _context.Events.FirstOrDefaultAsync(x => x.Id == id);
                model.EventId = id;

                if (@event != null)
                    model.EventName = @event.Name;

                model.News = await _context.News.Where(x => x.EventId == id).OrderByDescending(x => x.DateTime).ToListAsync();
            }

            return View(model);
        }


        public async Task<IActionResult> Details(int id)
        {
            var news = await _context.News
                .FirstOrDefaultAsync(m => m.Id == id);

            if (news == null)
                return NotFound();

            if (await UserAccessed(news.Event))
                ViewBag.Editer = true;

            return View(news);
        }

        public async Task<IActionResult> Create(int id)
        {
            var @event = await _context.Events.FirstOrDefaultAsync(x => x.Id == id);
            if (@event is null)
                return NotFound();
            if (!await UserAccessed(@event))
                return Unauthorized();

            var model = new NewsViewModel()
            {
                EventId = id,
                EventName = @event.Name
            };

            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(NewsViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var @event = await _context.Events.FirstOrDefaultAsync(x => x.Id == model.EventId);
            if (@event is null)
                return BadRequest();

            if (!await UserAccessed(@event))
                return Unauthorized();

            var newNews = new News()
            {
                DateTime = DateTime.Now,
                Description = model.Description,
                Event = @event,
                Image = model.PriviewImage,
                Title = model.Name,
                Sections = model.Sections is null ? null : new()
            };

            if (model.Sections is not null)
            {
                newNews.Sections = new();
                foreach (var item in model.Sections)
                {
                    if (item.Image is not null || item.Name != string.Empty || item.Description != string.Empty)
                    {
                        newNews.Sections.Add(new()
                        {
                            Title = item.Name,
                            Description = item.Description,
                            Image = item.Image,
                            News = newNews,
                        });
                    }
                }
            }

            _context.News.Add(newNews);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { Id = model.EventId });
        }

        public async Task<IActionResult> Edit(int id)
        {
            var news = await _context.News.FirstOrDefaultAsync(x => x.Id == id);
            if (news is null)
                return NotFound();

            if (!await UserAccessed(news.Event))
                return Unauthorized();

            var model = new NewsViewModel()
            {
                Id = id,
                EventId = id,
                EventName = news.Event.Name,
                PriviewImage = news.Image,
                Description = news.Description,
                Name = news.Title,
            };

            if (news.Sections is not null)
            {
                model.Sections = new();
                foreach (var item in news.Sections)
                {
                    model.Sections.Add(new()
                    {
                        Id = item.Id,
                        Name = item.Title,
                        Description = item.Description,
                        Image = item.Image,
                    });
                }
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(NewsViewModel model)
        {
            var news = await _context.News.FirstOrDefaultAsync(x => x.Id == model.Id);
            if (news is null)
                return NotFound();

            if (!await UserAccessed(news.Event))
                return Unauthorized();

            if (news.Image != model.PriviewImage && model.PriviewImage is not null)
                news.Image = model.PriviewImage;
            if (news.Title != model.Name)
                news.Title = model.Name;
            if (news.Description != model.Description)
                news.Description = model.Description;

            if (model.Sections is not null)
            {
                if (news.Sections is null)
                    news.Sections = new();

                foreach (var item in model.Sections)
                {
                    var newsSection = news.Sections.FirstOrDefault(x => x.Id == item.Id && item.Id != 0);
                    if (newsSection is not null)
                    {
                        if (item.ToDelete)
                            news.Sections.Remove(newsSection);
                        else
                        {
                            if (newsSection.Image != item.Image && item.Image is not null)
                                newsSection.Image = item.Image;
                            if (newsSection.Title != item.Name)
                                newsSection.Title = item.Name;
                            if (newsSection.Description != item.Description)
                                newsSection.Description = item.Description;
                        }
                    }
                    else
                    {
                        news.Sections.Add(new()
                        {
                            Title = item.Name,
                            Description = item.Description,
                            Image = item.Image,
                            News = news,
                        });
                    }
                }
            }

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Details), new { Id = model.Id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var news = await _context.News.FirstOrDefaultAsync(x => 
                x.Id == id);

            if (news is null)
                return BadRequest();

            if (!await UserAccessed(news.Event))
                return Unauthorized();

            _context.News.Remove(news);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index), new { Id = news.EventId });
        }
        public IActionResult GetParticipantEntry(int Index)
        {
            ViewBag.Index = Index;
            return PartialView("_NewsSectionEntry", Index);
        }
        private async Task<bool> UserAccessed(Event @event)
        {
            if (User.IsInRole("OrganizationUser"))
            {
                var user = await _userManager.GetUserAsync(User);
                if (user is not null)
                    if (@event.Organizations.Contains(((Models.Users.OrganizationUsers)user).Organization))
                        return true;
                return false;
            }
            return false;
        }
    }
}

Controllers/ServiceControllers/OrganizationsController.cs
using DiplomService.Database;
using DiplomService.ViewModels.OrganizationViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DiplomService.Controllers.ServiceControllers
{
    public class OrganizationsController : Controller
    {
        private readonly ApplicationContext _context;

        public OrganizationsController(ApplicationContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return _context.Organizations != null ?
                        View(await _context.Organizations.Where(x => x.ReadyToShow).ToListAsync()) :
                        Problem("Entity set 'ApplicationContext.Organizations'  is null.");
        }

        public async Task<IActionResult> Details(int? id)
        {
            var organization = await _context.Organizations.FirstOrDefaultAsync(x => x.Id == id);
            if (organization is null)
                return NotFound();

            OrganizationViewModel organizationViewModel = new()
            {
                Organization = organization,
            };

            return View(organizationViewModel);
        }

        [Authorize(Roles = "OrganizationUser")]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "OrganizationUser")]
        public async Task<IActionResult> Create(OrganizationViewModel organizationViewModel)
        {
            var organization = organizationViewModel.Organization;
            if (ModelState.IsValid)
            {
                _context.Add(organization);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(organization);
        }


        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id, string? returnUrl)
        {
            if (id == null || _context.Organizations == null)
            {
                return NotFound();
            }

            var Organization = await _context.Organizations.FirstOrDefaultAsync(x => x.Id == id);
            if (Organization == null)
            {
                return NotFound();
            }
            ViewBag.ReturnUrl = returnUrl;
            return View(Organization);
        }

        // POST: Chats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> DeleteConfirmed(int id, string? returnUrl)
        {
            if (_context.Organizations == null)
            {
                return Problem("Entity set 'ApplicationContext.Organizations'  is null.");
            }
            var Organization = await _context.Organizations.FirstOrDefaultAsync(x => x.Id == id);
            if (Organization != null)
            {
                _context.Organizations.Remove(Organization);
            }

            await _context.SaveChangesAsync();
            if (returnUrl != null)
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction(nameof(Index));
        }


        private bool OrganizationExists(int id)
        {
            return (_context.Organizations?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Admin/DeleteEvent.cshtml
@model Event;

@{
    Layout = "_Layout";
    ViewData["Title"] = "Удаление события";
}
@section Styles {
    <link rel="stylesheet" href="~/css/cabinetstyle.css" asp-append-version="true" />
}

<div class="intro" style="height:40vh">
    <div class="intro__column">
        <p class="intro__title">Удаление события @Model.Name</p>
    </div>
</div>

<div class="container">
    <div class="navigation-block">
        <partial name="_NavPartial" />
    </div>
    <p class="text-success">@ViewBag.Message</p>
    <p class="text-danger">@ViewBag.ErrorMessage</p>
    <form method="post">
        <div asp-validation-summary="All" class="text-danger"></div>
        <p>Укажите причину удаления.</p>
        <textarea name="reason" class="login-form__input textarea-input"></textarea>
        <input type="submit" value="Сохранить" class="btn btn-primary w-25 mt-3" />
    </form>
</div>

Views/Admin/Events.cshtml
@model IEnumerable<DiplomService.Models.Event>
@{
    Layout = "_Layout";
    ViewData["Title"] = "События";
}
@section Styles {
    <link rel="stylesheet" href="~/css/cabinetstyle.css" asp-append-version="true" />
}

<div class="intro" style="height:40vh">
    <div class="intro__column">
        <p class="intro__title">События</p>
    </div>
</div>



<div class="container">
    <div class="navigation-block">
        <partial name="_NavPartial" />
    </div>
    <div class="circled-search__block">
        <input type="text" class="circled-search__input">
    </div>


    <p class="fw-bold h4 measureTitle">Текущие события</p>
    <div class="items-section">
    @foreach (var item in Model.Where(x=>(x.DateOfEnd>=DateTime.Now || x.DateOfEnd is null) && x.ReadyToShow))
    {
        <div class="item-block my-3  justify-content-between align-items-center">
            <a asp-action="Details" asp-controller="Events" asp-route-id="@item.Id" class="d-flex endHiden multi-column-block">
                @if (item.PriviewImage != null)
                {
                    string? mimeType = item.MimeType; // MIME-тип по умолчанию

                    if (mimeType != null)
                    {
                        <img src="data:@mimeType;base64,@Convert.ToBase64String(item.PriviewImage)" alt="Image" class="item-block__image">
                    }
                }
                else
                {
                    <img src="/Images/camara.png" alt="Image" class="item-block__image">
                }
                <div class="item-block__column">
                    <p class="item-block__title">@item.Name</p>
                    <p class="item-block__text">
                    Организатор:
                    @{
                        string value = "";
                        item.Organizations.ForEach(x => value += x.Name + ",");
                        @value
                        ;
                    }
                    <p class="item-block__text">Дата проведения: @item.DateOfStart.ToShortDateString()</p>
                    <p class="item-block__text">
                    Дата окончания:
                    @{
                        if (item.DateOfEnd != null)
                        {
                            @item.DateOfEnd.Value.ToShortDateString()
                            ;
                        }
                        else
                        {
                            @("Не указана")
                            ;
                        }
                    }
                    </p>
                    <p class="item-block__text">Участников: @item.EventMembers</p>
                    @if (!item.ReadyToShow)
                    {
                        <p class="item-block__text">Не опубликовано</p>
                    }
                </div>
            </a>
            <a asp-action="DeleteEvent" asp-route-id="@item.Id" class="d-block login-form__submit">Удалить</a>
        </div>
    }
    </div>

    <p class="fw-bold h4 measureTitle">Требуют заполнения</p>
    <div class="items-section">
    @foreach (var item in Model.Where(x => !x.ReadyToShow))
    {
        <div class="item-block my-3  justify-content-between align-items-center">
                <a asp-action="Details" asp-controller="Events" asp-route-id="@item.Id" class="d-flex endHiden multi-column-block">
                    @if (item.PriviewImage != null)
                    {
                        string? mimeType = item.MimeType; // MIME-тип по умолчанию

                        if (mimeType != null)
                        {
                            <img src="data:@mimeType;base64,@Convert.ToBase64String(item.PriviewImage)" alt="Image" class="item-block__image">
                        }
                    }
                    else
                    {
                        <img src="/Images/camara.png" alt="Image" class="item-block__image">
                    }
                    <div class="item-block__column">
                        <p class="item-block__title">@item.Name</p>
                        <p class="item-block__text">
                            Организатор:
                            @{
                                string value = "";
                                item.Organizations.ForEach(x => value += x.Name + ",");
                                @value
                                ;
                            }
                        <p class="item-block__text">Дата проведения: @item.DateOfStart.ToShortDateString()</p>
                        <p class="item-block__text">
                            Дата окончания:
                                @{
                                    if (item.DateOfEnd != null)
                                    {
                                        @item.DateOfEnd.Value.ToShortDateString()
                                        ;
                                    }
                                    else
                                    {
                                        @("Не указана")
                                        ;
                                    }
                                }
                        </p>
                        <p class="item-block__text">Участников: @item.EventMembers</p>
                            @if (!item.ReadyToShow)
                            {
                            <p class="item-block__text">Не опубликовано</p>
                            }

                    </div>
                </a>
            <div>
                <a asp-action="DeleteEvent" asp-route-id="@item.Id" class="d-block login-form__submit btn-danger">Удалить</a>
            </div>
        </div>
    }
    </div>

    <p class="fw-bold h4 measureTitle">Завершенные события</p>
    <div class="items-section">
    @foreach (var item in Model.Where(x => x.DateOfEnd < DateTime.Now))
    {
        <div class="item-block my-3  justify-content-between align-items-center">
            <a asp-action="Details" asp-controller="Events" asp-route-id="@item.Id" class="d-flex endHiden multi-column-block">
                    @if (item.PriviewImage != null)
                    {
                        string? mimeType = item.MimeType; // MIME-тип по умолчанию

                        if (mimeType != null)
                        {
                            <img src="data:@mimeType;base64,@Convert.ToBase64String(item.PriviewImage)" alt="Image" class="item-block__image">
                        }
                    }
                    else
                    {
                        <img src="/Images/camara.png" alt="Image" class="item-block__image">
                    }
                    <div class="item-block__column">
                        <p class="item-block__title">@item.Name</p>
                        <p class="item-block__text">
                            Организатор:
                            @{
                                string value = "";
                                item.Organizations.ForEach(x => value += x.Name + ",");
                                @value
                                ;
                            }
                        <p class="item-block__text">Дата проведения: @item.DateOfStart.ToShortDateString()</p>
                        <p class="item-block__text">
                            Дата окончания:
                                @{
                                    if (item.DateOfEnd != null)
                                    {
                                        @item.DateOfEnd.Value.ToShortDateString()
                                        ;
                                    }
                                    else
                                    {
                                        @("Не указана")
                                        ;
                                    }
                                }
                        </p>
                        <p class="item-block__text">Участников: @item.EventMembers</p>
                            @if (!item.ReadyToShow)
                            {
                            <p class="item-block__text">Не опубликовано</p>
                            }

                    </div>
                </a>
            <div>
                    <a asp-action="DeleteEvent" asp-route-id="@item.Id" class="d-block login-form__submit btn-danger">Удалить</a>
            </div>
        </div>
    }
    </div>
</div>
    

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/searchScript.js"></script>
    <script src="~/js/searchInputPopUp.js"></script>
    <script src="/js/slideItemScript.js"></script>
}

Views/Admin/News.cshtml
@model List<DiplomService.Models.News>
@{
    Layout = "_Layout";
    ViewData["Title"] = "Новости";
}
@section Styles {
    <link rel="stylesheet" href="~/css/cabinetstyle.css" asp-append-version="true" />
}

<div class="intro" style="height:40vh">
    <div class="intro__column">
        <p class="intro__title">Новости</p>
    </div>
</div>
<div class="container">
    <div class="navigation-block">
        <partial name="_NavPartial" />
    </div>
    @foreach (var item in Model)
    {
        <div class="item-block my-3  justify-content-between align-items-center">
            <a asp-action="Details" asp-controller="News" asp-route-id="@item?.Id" class="d-flex endHiden multi-column-block">
                @if (item.Image != null)
                {
                    string? mimeType = item.MimeType; // MIME-тип по умолчанию

                    if (mimeType != null)
                    {
                        <img src="data:@mimeType;base64,@Convert.ToBase64String(item.Image)" alt="Image" class="item-block__image">
                    }
                }
                else
                {
                    <img src="/Images/camara.png" alt="Image" class="item-block__image">
                }
                <div class="item-block__column">
                    <p class="item-block__title">@item.Title</p>
                    <p class="item-block__text">
                        @item.Description
                    </p>
                    <p class="item-block__text">@item.DateTime.ToShortDateString()</p>
                </div>
            </a>
            <div>
                <form method="post" asp-action="DeleteNews">
                    <input type="hidden" asp-for="@item.Id"/>
                    <input type="submit" class="d-block login-form__submit btn-danger" value="Удалить"/>
                </form>
                
            </div>
        </div>
    }
</div>

Views/Admin/Organizations.cshtml
@model List<DiplomService.Models.Organization>
@{
    Layout = "_Layout";
    ViewData["Title"] = "Организации";
}
@section Styles {
    <link rel="stylesheet" href="~/css/cabinetstyle.css" asp-append-version="true" />
}

<div class="intro" style="height:40vh">
    <div class="intro__column">
        <p class="intro__title">Организации</p>
    </div>
</div>
<div class="container">
    <div class="navigation-block">
        <partial name="_NavPartial" />
    </div>
    <div class="circled-search__block">
        <input type="text" class="circled-search__input">
    </div>

    @foreach (var item in Model)
    {
        <div class="item-block my-3  justify-content-between align-items-center">
            <a asp-action="Details" asp-controller="Organizations" asp-route-id="@item?.Id" class="d-flex endHiden multi-column-block">
                @if (item.Preview != null)
                {
                    string? mimeType = item.MimeType;

                    if (mimeType != null)
                    {
                        <img src="data:@mimeType;base64,@Convert.ToBase64String(item.Preview)" alt="Image" class="item-block__image">
                    }
                }
                else
                {
                    <img src="/Images/camara.png" alt="Image" class="item-block__image">
                }
                <div class="item-block__column">
                    <p class="item-block__title name">@item.Name</p>
                    <p class="item-block__text">
                        @item.Description
                    </p>
                </div>
            </a>
            <div>
                <a asp-action="DeleteOrganization" asp-route-id="@item.Id" class="d-block login-form__submit btn-danger">Удалить</a>
            </div>
        </div>
        
    }
</div>

@section Scripts{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/searchScript.js"></script>
    <script src="~/js/searchInputPopUp.js"></script>
}