Models/EventsFolder/Division/Measure.cs
using DiplomService.Models.EventsFolder.Division;
using DiplomService.Services;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace DiplomService.Models
{
    public class Measure
    {
        [Key]
        public int Id { get; set; }
        public byte[]? Icon { get; set; }
        [Required(ErrorMessage = "Не указано имя")]
        public string Name { get; set; } = "";

        [Required(ErrorMessage = "Не указано место проведения")]
        public string Place { get; set; } = "";

        public string? Descrition { get; set; } = "";

        public TimeSpan Length { get; set; } = TimeSpan.Zero;

        [Required(ErrorMessage = "Пропущен пункт")]
        public bool SameForAll { get; set; } = true;

        [Required]
        public bool OneTime { get; set; } = false;
        [Required]
        public bool WeekDays { get; set; } = false;

        public int EventId { get; set; }

        [Required]
        [ForeignKey("EventId")]
        [JsonIgnore]
        public virtual Event Event { get; set; } = new();
        public virtual List<MeasureDivisionsInfo> MeasureDivisionsInfos { get; set; } = new();

        public string? MimeType { get { return ImageWorker.GetImageMimeType(Icon); } }
    }
}

ViewModels/Measures/EventMeasuresViewModel.cs
using DiplomService.Services;

namespace DiplomService.ViewModels.Measures
{
    public class EventMeasuresViewModel
    {
        public int Id { get; set; }
        public byte[]? Icon { get; set; }
        public string EventName { get; set; } = "";
        public DateTime DateTime { get; set; }
        public bool SameForAll { get; set; }
        public TimeSpan Length { get; set; } = TimeSpan.Zero;
        public string? MimeType { get { return ImageWorker.GetImageMimeType(Icon); } }
    }
}

ViewModels/Measures/MeasureDatesViewModel.cs
namespace DiplomService.ViewModels
{
    public class MeasureDatesViewModel
    {
        public int Id { get; set; }
        public DateTime Datetime { get; set; }
        public string? Place { get; set; } = "";
    }
}

ViewModels/Measures/MeasureDaysViewModel.cs
namespace DiplomService.ViewModels
{
    public class MeasureDaysViewModel
    {
        public int Id { get; set; }
        public TimeSpan TimeSpan { get; set; } = TimeSpan.Zero;
        public bool Checked { get; set; } = false;
        public int DayNumber { get; set; }
        public string? Place { get; set; }
    }
}

ViewModels/Measures/MeasureViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace DiplomService.ViewModels.Measures
{
    public class MeasureViewModel
    {
        [Key]
        public int Id { get; set; }
        public byte[]? Icon { get; set; }
        [Required(ErrorMessage = "Не указано имя")]
        public string Name { get; set; } = "";

        [Required(ErrorMessage = "Не указано место проведения")]
        public string Place { get; set; } = "";

        [Required]
        public bool OneTime { get; set; } = true;

        [Required]
        public bool WeekDays { get; set; } = false;

        public string? Descrition { get; set; } = "";

        public TimeSpan Length { get; set; } = TimeSpan.Zero;

        public bool SameForAll { get; set; } = false;


        private IFormFile? iconImageFile;
        [Display(Name = "Иконка мероприятия")]
        public IFormFile? IconImageFile
        {
            get { return iconImageFile; }
            set
            {
                iconImageFile = value;
                if (value != null)
                {
                    using var memoryStream = new MemoryStream();

                    value.CopyTo(memoryStream);
                    Icon = memoryStream.ToArray();
                }
            }
        }

        public int EventId { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public bool DivisionsExists { get; set; } = true;

        public virtual List<MeasureDatesViewModel> MeasureDates { get; set; } = new();
        public virtual List<MeasureDaysViewModel> MeasureDays { get; set; } = new();

    }
}

Controllers/ApiContollers/MeasuresController.cs
using DiplomService.Database;
using DiplomService.Models;
using DiplomService.Models.EventsFolder.Division;
using DiplomService.ViewModels.Measures;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DiplomService.Controllers.ApiContollers
{
    [Route("api/[controller]")]
    [ApiController]
    [Authorize(Roles = "MobileUser")]
    public class MeasuresController : ControllerBase
    {
        private readonly ApplicationContext _context;
        private readonly UserManager<User> _userManager;

        public MeasuresController(ApplicationContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: api/Measures
        [HttpGet("GetMeasures")]
        public async Task<ActionResult> GetMeasures()
        {
            if (_context.Measures == null)
            {
                return NotFound();
            }
            return Ok(await _context.Measures.ToListAsync());
        }

        [HttpGet("GetMeasuresForUser")]
        public async Task<ActionResult> GetMeasuresForUser()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound();
            }
            else
            {
                var divisions = await _context.Users
                    .Where(u => u == user)
                    .SelectMany(u => u.UserDivisions)
                    .Select(du => du.Division).ToListAsync();

                var measures = divisions.SelectMany(x => x.Event.Measures).Where(x => x.SameForAll).SelectMany(x => x.MeasureDivisionsInfos).Distinct().ToList();
                measures.AddRange(divisions.SelectMany(x => x.MeasureDivisionsInfos).ToList());


                List<MeasureDates> measureDates = new List<MeasureDates>();
                List<EventMeasuresViewModel> viewModel = new List<EventMeasuresViewModel>();
                foreach (var item in measures)
                {
                    if (!item.WeekDays)
                    {
                        measureDates.AddRange(item.MeasureDates);
                    }
                    else
                    {
                        measureDates.AddRange(GetNearestDayOfWeek(item.MeasureDays));
                    }

                }
                measureDates = measureDates.OrderBy(x => x.Datetime).ToList();
                foreach (var item in measureDates)
                {
                    viewModel.Add(new EventMeasuresViewModel()
                    {
                        Id = item.MeasureDivisionsInfosId,
                        SameForAll = item.MeasureDivisionsInfos.SameForAll,
                        EventName = item.MeasureDivisionsInfos.Measure.Name,
                        DateTime = item.Datetime,
                        Icon = item.MeasureDivisionsInfos.Measure.Icon
                    });
                }

                return Ok(viewModel);
            }
        }

        [HttpPost("GetMeasuresDivision")]
        public async Task<ActionResult> GetMeasuresDivision([FromBody] List<int> divisions)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user is null)
            {
                return NotFound();
            }
            else
            {
                List<EventMeasuresViewModel> viewModel = new List<EventMeasuresViewModel>();
                List<MeasureDivisionsInfo> measuresForDivision = new List<MeasureDivisionsInfo>();
                for (int i = 0; i < divisions.Count; i++)
                {
                    var division = await _context.Divisions.FirstOrDefaultAsync(x => x.Id == divisions[i]);
                    if (division == null)
                        return NotFound();
                    if (i == 0)
                    {
                        measuresForDivision.AddRange(division.Event.Measures.Where(x => x.SameForAll)
                              .SelectMany(x => x.MeasureDivisionsInfos).ToList());
                    }
                    measuresForDivision.AddRange(division.MeasureDivisionsInfos);
                }

                foreach (var measure in measuresForDivision)
                {
                    var viewModelItem = new EventMeasuresViewModel()
                    {
                        Id = measure.Id,
                        EventName = measure.Measure.Name,
                    };
                    if (measure.WeekDays)
                    {
                        viewModelItem.DateTime = GetNearestDate(measure.MeasureDays);
                    }
                    else
                    {
                        viewModelItem.DateTime = GetNearestDate(measure.MeasureDates);
                    }
                    viewModelItem.Icon = measure.Measure.Icon;
                    if (viewModelItem.DateTime>DateTime.UtcNow)
                    {
                        viewModel.Add(viewModelItem);
                    }
                }

                viewModel = viewModel.OrderBy(x => x.DateTime).ToList();
                return Ok(viewModel);
            }
        }

        // GET: api/Measures/5
        [HttpGet("GetMeasure/{id}")]
        public async Task<ActionResult<MeasureDivisionsInfo>> GetMeasure(int id)
        {
            if (_context.Measures == null)
            {
                return NotFound();
            }
            var measure = await _context.MeasureDivisionsInfos.FindAsync(id);

            if (measure == null)
            {
                return NotFound();
            }
            measure.Length = measure.Measure.Length;
            measure.Place = measure.Measure.Place;
            if (measure.WeekDays)
                measure.MeasureDays = measure.MeasureDays.OrderBy(x => x.DayNumber).ToList();
            else
                measure.MeasureDates = measure.MeasureDates.OrderBy(x => x.Datetime).ToList();

            return Ok(measure);
        }

        public static DateTime GetNearestDate(List<MeasureDates> measureDates)
        {
            DateTime currentDate = DateTime.Now;
            var validDates = measureDates
                .Where(date => date.Datetime > currentDate)
                .OrderBy(date => Math.Abs((date.Datetime - currentDate).TotalDays))
                .FirstOrDefault();

            return validDates != null ? validDates.Datetime : DateTime.MinValue;
        }
        public static DateTime GetNearestDate(List<MeasureDays> measureDays)
        {
            DateTime currentDate = DateTime.Now;
            int currentDayOfWeek = (int)currentDate.DayOfWeek;

            var sortedDatesList = measureDays
                .Select(day =>
                {
                    var nextDay = currentDate.Date.AddDays((day.DayNumber - currentDayOfWeek + 7) % 7);
                    var dateTime = nextDay.Add(day.TimeSpan);
                    return new MeasureDates
                    {
                        Datetime = dateTime,
                        Place = day.Place,
                        MeasureDivisionsInfos = day.MeasureDivisionsInfo
                    };
                })
                .Where(date => date.Datetime > currentDate)
                .OrderBy(date => date.Datetime)
                .ToList();
            return sortedDatesList.FirstOrDefault()?.Datetime ?? DateTime.MinValue;
        }
        public static List<MeasureDates> GetNearestDayOfWeek(List<MeasureDays> measureDays)
        {
            DateTime currentDate = DateTime.Now;
            int currentDayOfWeek = (int)currentDate.DayOfWeek;

            var sortedDatesList = measureDays
                .Select(day =>
                {
                    var nextDay = currentDate.Date.AddDays((day.DayNumber - currentDayOfWeek + 7) % 7);
                    var dateTime = nextDay.Add(day.TimeSpan);

                    return new MeasureDates
                    {
                        Datetime = dateTime,
                        Place = day.Place,
                        MeasureDivisionsInfos = day.MeasureDivisionsInfo
                    };
                })
                .Where(date => date.Datetime > currentDate)
                .OrderBy(date => date.Datetime)
                .ToList();
            return sortedDatesList;
        }
    }
}

Views/Measures/Index.cshtml
@model Event

@using DiplomService.ViewModels;
@using DiplomService.ViewModels.Measures;
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    int eventId = 0;
    if (ViewBag.eventId != null)
    {
        eventId = ViewBag.eventId;
    }
}
<div class="intro" style="height:40vh">
    <div class="intro__column">
        <p class="intro__title">Заполните данные о расписании</p>
    </div>
</div>
<div class="container">
    <div class="navigation-block">
        <a asp-action="Edit" asp-controller ="Events" asp-route-id="@Model.Id" class="cabinet-nav__item">Событие</a>
        <a asp-action="Index" asp-controller="Measures" asp-route-id="@Model.Id" class="cabinet-nav__item">Расписание</a>
        @if (Model.DivisionsExist)
        {
            <a asp-action="Index" asp-controller="Divisions" asp-route-id="@Model.Id" class="cabinet-nav__item">Подразделения</a>
        }
        else
        {
            <a asp-action="Members" asp-controller="Divisions" asp-route-id="@Model.Divisions[0].Id" class="cabinet-nav__item">Участники</a>
        }
    </div>
    <p class="display-6">Добавьте расписание</p>
    <div class="circled-search__block">
        <input type="text" class="circled-search__input">
    </div>
    @{
        if (Model.Measures.Count > 0)
        {
            @foreach (var item in Model.Measures)
            {
                <a asp-action="Edit" asp-route-id="@item?.Id" class="item-block my-3 align-items-center ">
                    @if (item.Icon != null)
                    {
                        string? mimeType = item.MimeType;

                        if (mimeType != null)
                        {
                            <img src="data:@mimeType;base64,@Convert.ToBase64String(item.Icon)" alt="Image" class="item-block__image">
                        }
                    }
                    else
                    {
                        <img src="/Images/camara.png" alt="Image" class="item-block__image">
                    }
                    <div class="item-block__column">
                        <p class="item-block__title name">@item.Name</p>
                        <p class="item-block__text">Основное место проведения: @item.Place</p>
                        <p class="item-block__text">Продолжительность: @item.Length</p>
                        @if (Model.DivisionsExist)
                        {
                            string type = item.SameForAll ? "Всеобщее" : "Обычное";
                            <p class="item-block__text">Вид мероприятия: @type</p>
                        }
                    </div>
                </a>
            }
        }
        else
        {
            <p class="align-content-center">Настройте расписание проводимого события</p>
        }
        <a href="/Measures/Create/@eventId" class="btn btn-primary w-25 mt-3">
            Добавить мероприятие
        </a>

        <div class="d-flex justify-content-between">
            @{
                string submitValue = Model.DivisionsExist ? "Далее" : "Опубликовать";
                string path = Model.DivisionsExist ? $"/Divisions/Index/{@Model.Id}" : $"/Events/Publish/{@Model.Id}";
                <a href="/Events/Edit/@Model.Id?returnUrl=/Measures/Index/@Model.Id" class="btn btn-primary my-3 w-25">Назад</a>
                <a href="@path" class="btn btn-primary my-3 w-25">@submitValue</a>
            }
        </div>
    }
</div>
@section Faq {
    <div id="faq">
    </div>
    <div id="faq-body">
        <p class="h5 fw-bold">Расписание</p>
        <p class=" h6 fw-bold">На этой странице будут отображатся созданные мероприятия.</p>
        <p class="fw-bold">Добавление:</p>
        <ul>
            <li>
                Нажмите кнопку "Добавить мероприятие".
            </li>
            <li>
                Заполните информацию на странице, на которую перейдете.
            </li>
            <li>
                Добавьте все требуемые мероприятия и нажмите "@submitValue".
            </li>
        </ul>
    </div>
}
@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/searchScript.js"></script>
    <script src="~/js/searchInputPopUp.js"></script>
}