Models/EventsFolder/Division/Division.cs
using DiplomService.Models.EventsFolder.Division;
using DiplomService.Services;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace DiplomService.Models
{
    public class Division
    {
        [Key]
        public int Id { get; set; }

        public byte[]? PreviewImage { get; set; } = null;

        [Required]
        [MaxLength(50)]
        public string Name { get; set; } = "";

        [MaxLength(250)]
        public string? Description { get; set; }

        [Required]
        public DateTime DateOfStart { get; set; }

        public DateTime? DateOfEnd { get; set; } = null;

        [Range(-180, 180)]
        public double Longitude { get; set; }
        [Range(-90, 90)]
        public double Latitude { get; set; }
        public string PlaceName { get; set; } = "";

        public int EventId { get; set; }

        [JsonIgnore]
        public virtual Event Event { get; set; } = new();
        [JsonIgnore]
        public virtual List<MeasureDivisionsInfo> MeasureDivisionsInfos { get; set; } = new();
        [JsonIgnore]
        public virtual List<DivisionUsers> DivisionMembers { get; set; } = new();
        [NotMapped]
        public bool DivisionLeaderExist { get { return DivisionMembers.Any(x => x.DivisionDirector); } }

        [NotMapped]
        public string? MimeType { get { return ImageWorker.GetImageMimeType(PreviewImage); } }

    }
}

Models/EventsFolder/Division/DivisionUsers.cs
using Microsoft.Build.Framework;
using System.Text.Json.Serialization;

namespace DiplomService.Models
{
    public class DivisionUsers
    {
        public int Id { get; set; }
        public int DivisionId { get; set; }
        [Required]
        [JsonIgnore]
        public virtual Division Division { get; set; } = new();
        public string UserId { get; set; } = "";
        [Required]
        [JsonIgnore]
        public virtual User User { get; set; } = new();
        [Required]
        public bool DivisionDirector { get; set; } = false;
    }
}

Models/EventsFolder/Division/Measure.cs
using DiplomService.Models.EventsFolder.Division;
using DiplomService.Services;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace DiplomService.Models
{
    public class Measure
    {
        [Key]
        public int Id { get; set; }
        public byte[]? Icon { get; set; }
        [Required(ErrorMessage = "Не указано имя")]
        public string Name { get; set; } = "";

        [Required(ErrorMessage = "Не указано место проведения")]
        public string Place { get; set; } = "";

        public string? Descrition { get; set; } = "";

        public TimeSpan Length { get; set; } = TimeSpan.Zero;

        [Required(ErrorMessage = "Пропущен пункт")]
        public bool SameForAll { get; set; } = true;

        [Required]
        public bool OneTime { get; set; } = false;
        [Required]
        public bool WeekDays { get; set; } = false;

        public int EventId { get; set; }

        [Required]
        [ForeignKey("EventId")]
        [JsonIgnore]
        public virtual Event Event { get; set; } = new();
        public virtual List<MeasureDivisionsInfo> MeasureDivisionsInfos { get; set; } = new();

        public string? MimeType { get { return ImageWorker.GetImageMimeType(Icon); } }
    }
}

Models/EventsFolder/Division/MeasureDates.cs
using System.Text.Json.Serialization;

namespace DiplomService.Models.EventsFolder.Division
{
    public class MeasureDates
    {
        public int Id { get; set; }
        public DateTime Datetime { get; set; }
        public int MeasureDivisionsInfosId { get; set; }
        [JsonIgnore]
        public virtual MeasureDivisionsInfo MeasureDivisionsInfos { get; set; } = new();
        public string? Place { get; set; } = "";
    }
}

Models/EventsFolder/Division/MeasureDays.cs
using System.Text.Json.Serialization;

namespace DiplomService.Models.EventsFolder.Division
{
    public class MeasureDays
    {
        public int Id { get; set; }
        public TimeSpan TimeSpan { get; set; }
        public int DayNumber { get; set; }
        public int MeasureDivisionsInfoId { get; set; }
        [JsonIgnore]
        public virtual MeasureDivisionsInfo MeasureDivisionsInfo { get; set; } = new();
        public string? Place { get; set; }
    }
}

Models/EventsFolder/Division/MeasureDivisionsData.cs
namespace DiplomService.Models
{
    public class MeasureDivisionsData
    {
        public int DivisionId { get; set; }
        public DateTime DateTime { get; set; }
        public string? Place { get; set; }
    }
}

Controllers/ApiContollers/DivisionsController.cs
using DiplomService.Database;
using DiplomService.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DiplomService.Controllers.ApiContollers
{
    [Route("api/[controller]")]
    [ApiController]
    [Authorize]
    public class DivisionsController : ControllerBase
    {
        private readonly ApplicationContext _context;
        private readonly UserManager<User> _userManager;

        public DivisionsController(ApplicationContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }


        [HttpGet("GetDivisions")]
        public async Task<ActionResult<IEnumerable<Division>>> GetDivisions()
        {
            if (_context.Divisions == null)
            {
                return NotFound();
            }
            return await _context.Divisions.ToListAsync();
        }
        [HttpGet("GetDivisionForUser/{eventId}")]
        public async Task<ActionResult<IEnumerable<Division>>> GetDivisionForUser(int eventId)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user is null)
            {
                return NotFound();
            }
            var divisions = await _context.Divisions
                .Where(d => d.EventId == eventId)
                .Where(d => d.DivisionMembers.Any(du => du.UserId == user.Id))
                .ToListAsync();

            return Ok(divisions);
        }
        // GET: api/Divisions/5
        [HttpGet("GetDivision/{id}")]
        public async Task<ActionResult> GetDivision(int id)
        {
            
            Console.WriteLine("Запрос получен в: " + DateTime.Now.Hour + ":" + 
                DateTime.Now.Minute + ":" + DateTime.Now.Second + ":" + DateTime.Now.Millisecond);
            if (_context.Divisions == null)
            {
                return NotFound();
            }
            var division = await _context.Divisions.FirstOrDefaultAsync(x=>x.Id==id);

            if (division == null)
            {
                return NotFound();
            }
            Console.WriteLine("Ответ отправлен в: " + DateTime.Now.Hour + ":" + DateTime.Now.Minute + ":" 
                + DateTime.Now.Second + ":" + DateTime.Now.Millisecond);
            return Ok(division);
        }
    }
}

Controllers/ServiceControllers/DivisionsController.cs
using DiplomService.Database;
using DiplomService.Models;
using DiplomService.Models.EventsFolder.Division;
using DiplomService.Models.Users;
using DiplomService.Services;
using DiplomService.ViewModels;
using DiplomService.ViewModels.Divisions;
using DiplomService.ViewModels.Email;
using DiplomService.ViewModels.EventApplication;
using DiplomService.ViewModels.Measures;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;

namespace DiplomService.Controllers
{

    public class DivisionsController : Controller
    {
        private readonly ApplicationContext _context;
        private readonly UserManager<User> _userManager;
        public DivisionsController(ApplicationContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(int id)
        {
            var @event = await _context.Events.FirstOrDefaultAsync(x => x.Id == id);
            if (@event == null)
                return BadRequest();

            return View(@event);
        }
        public async Task<IActionResult> Details(int id)
        {
            var division = await _context.Divisions.FirstOrDefaultAsync(x => x.Id == id);
            if (division == null)
                return NotFound();
            return View(division);
        }

        [Authorize(Roles = "OrganizationUser")]
        public async Task<IActionResult> Members(int id)
        {
            var division = await _context.Divisions.FirstOrDefaultAsync(x => x.Id == id);
            if (division is null)
                return NotFound();

            var user = await _userManager.GetUserAsync(User) as OrganizationUsers;
            if (user is null)
                return BadRequest();

            if (!division.Event.Organizations.Contains(user.Organization))
                return Unauthorized();

            var model = division.DivisionMembers.ToList();
            ViewBag.divisionId = id;
            return View(model);
        }

        [Authorize(Roles = "OrganizationUser")]
        public async Task<IActionResult> AddDivisionMember(int id, bool leader = false)
        {
            var division = await _context.Divisions.FirstOrDefaultAsync(x => x.Id == id);
            if (division is null)
                return NotFound();

            var user = await _userManager.GetUserAsync(User) as OrganizationUsers;
            if (user is null)
                return BadRequest();

            if (!division.Event.Organizations.Contains(user.Organization))
                return Unauthorized();
            var model = new ApplicationDataViewModel() { DivisionId = division.Id, DivisionLeader = leader };
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "OrganizationUser")]
        public async Task<IActionResult> AddDivisionMember(ApplicationDataViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var division = await _context.Divisions.FirstOrDefaultAsync(x => x.Id == model.DivisionId);
            if (division is null)
                return NotFound();

            var user = await _userManager.GetUserAsync(User) as OrganizationUsers;
            if (user is null)
                return BadRequest();

            if (!division.Event.Organizations.Contains(user.Organization))
                return Unauthorized();

            if (model.UserId is not null)
            {
                var divisionUser = await _userManager.FindByIdAsync(model.UserId);
                if (divisionUser is not null)
                {
                    if (!division.DivisionMembers.Any(x => x.User == divisionUser))
                    {
                        _context.DivisionUsers.Add(new()
                        {
                            Division = division,
                            User = divisionUser,
                            DivisionDirector = model.DivisionLeader
                        });
                        await _context.SaveChangesAsync();
                    }

                }
                else
                {
                    return NotFound();
                }
            }
            else
            {
                if (model.Name.Split().Length != 3)
                    ModelState.AddModelError("", "Укажите полное фио");
                if (model.PhoneNumber is null)
                    ModelState.AddModelError("", "Укажите номер телефона");
                if (model.Email is null)
                    ModelState.AddModelError("", "Укажите почтовый адрес");
                if (model.WorkingPlace is null)
                    ModelState.AddModelError("", "Укажите учебное заведение");
                if (_context.Users.Any(x => x.PhoneNumber == model.PhoneNumber))
                    ModelState.AddModelError("", "Пользователь с таким номером телефона уже зарегистрирован");

                if (!ModelState.IsValid || model.PhoneNumber is null || model.Email is null || model.Name.Split().Length != 3 || model.WorkingPlace is null)
                    return View(model);

                var nameParts = model.Name.Split();
                Models.User mobileUser;
                if (!model.DivisionLeader)
                {
                    if (model.Course is null)
                        ModelState.AddModelError("", "Укажите класс/курс");
                    if (model.Birthday is null)
                        ModelState.AddModelError("", "Укажите дату рождения");
                    if (!ModelState.IsValid || model.Birthday is null || model.Course is null)
                        return View(model);

                    mobileUser = new MobileUser()
                    {
                        Birthday = model.Birthday.Value,
                        Course = model.Course.Value,
                        Email = model.Email,
                        SecondName = nameParts[0],
                        Name = nameParts[1],
                        LastName = nameParts[2],
                        PhoneNumber = PhoneWorker.NormalizePhone(model.PhoneNumber),
                        UserName = PhoneWorker.NormalizePhone(model.PhoneNumber),
                        NormalizedUserName = PhoneWorker.NormalizePhone(model.PhoneNumber),
                        WorkingPlace = model.WorkingPlace,
                    };
                }
                else
                {

                    mobileUser = new WebUser()
                    {
                        Email = model.Email,
                        SecondName = nameParts[0],
                        Name = nameParts[1],
                        LastName = nameParts[2],
                        PhoneNumber = PhoneWorker.NormalizePhone(model.PhoneNumber),
                        UserName = model.Email,
                        NormalizedUserName = model.Email.ToUpper(),
                        WorkingPlace = model.WorkingPlace,
                    };
                }


                var createResult = await _userManager.CreateAsync(mobileUser);
                if (createResult.Succeeded)
                {
                    _context.DivisionUsers.Add(new()
                    {
                        Division = division,
                        User = mobileUser,
                        DivisionDirector = model.DivisionLeader
                    });
                    _context.SaveChanges();
                    if (model.DivisionLeader)
                    {
                        string password = Guid.NewGuid().ToString().Replace("-", string.Empty)[..5];
                        password += password.ToUpper() + '!' + "aWeA";

                        await _userManager.AddToRoleAsync(mobileUser, "WebUser");
                        await _userManager.AddPasswordAsync(mobileUser, password);


                        var messageVM = new ApplicationEmailViewModel()
                        {
                            OrganizationName = user.Organization.Name,
                            DateOfSend = DateTime.Now,
                            EmailToSend = mobileUser.Email,
                            Password = password,
                            PhoneNumber = mobileUser.PhoneNumber,
                            BaseUrl = $"{Request.Scheme}://{Request.Host}" + Url.Action("Login", "Account")
                        };

                        var renderer = HttpContext.RequestServices.GetRequiredService<IRazorViewToStringRenderer>();
                        var htmlMessage = await renderer.RenderViewToStringAsync("HtmlTemplates/DivisionLeaderRegistration", messageVM, HttpContext.RequestServices);
                        SmtpService.SendApplicationResponse(htmlMessage, messageVM);
                    }
                    else
                    {
                        await _userManager.AddToRoleAsync(mobileUser, "MobileUser");
                    }
                }
                else
                {
                    foreach (var item in createResult.Errors.Select(x => x.Description.ToString()))
                    {
                        ModelState.AddModelError("", item);
                    }
                    return View(model);
                }

            }

            return RedirectToAction(nameof(Members), new { division.Id });
        }



        [Authorize(Roles = "OrganizationUser")]
        public async Task<IActionResult> Create(int id)
        {
            var @event = await _context.Events.FirstOrDefaultAsync(x => x.Id == id);
            if (@event == null)
                return NotFound();

            var model = new DivisionViewModel()
            {
                StartDate = @event.DateOfStart,
                EndDate = @event.DateOfEnd,
                EventId = @event.Id,
            };

Views/Divisions/AddDivisionMember.cshtml
@model DiplomService.ViewModels.EventApplication.ApplicationDataViewModel

@{
    ViewData["Title"] = "Добавление участника";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="intro" style="height:50vh">
    <div class="intro__column">
        <p class="intro__title">Добавление участника</p>
    </div>
</div>
<div class="container">
    <form method="post" enctype="multipart/form-data" id="applicationForm">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="DivisionId"/>
        <input type="hidden" asp-for="UserId" />
        <input type="hidden" asp-for="DivisionLeader"/>
        <div class="form-group my-2 position-relative">
            <label asp-for="Name" class="control-label">ФИО*</label>
            <input asp-for="Name" class="login-form__input form-control userSuggestionInput"/>
            <span asp-validation-for="Name" class="text-danger"></span>

            <div class="suggestionsUserDropdown" style="position: absolute; display: none; z-index:10"></div>
        </div>

        <div id="additionalInfo">
            @if (!Model.DivisionLeader)
            {
                <div class="form-group my-2">
                    <label asp-for="Course" class="control-label">Курс или класс*</label>
                    <input asp-for="Course" class="login-form__input form-control" />
                    <span asp-validation-for="Course" class="text-danger"></span>
                </div>
                <div class="form-group my-2">
                    <label asp-for="Birthday" class="control-label">Дата рождения*</label>
                    <input asp-for="Birthday" type="date" class="login-form__input form-control" />
                    <span asp-validation-for="Birthday" class="text-danger"></span>
                </div>
            }
            <div class="form-group my-2">
                <label asp-for="WorkingPlace" class="control-label">Учебное заведение*</label>
                <input asp-for="WorkingPlace" class="login-form__input form-control" />
                <span asp-validation-for="WorkingPlace" class="text-danger"></span>
            </div>
            <div class="form-group my-2">
                <label asp-for="PhoneNumber" class="control-label">Номер телефона*</label>
                <input asp-for="PhoneNumber" type="tel" class="login-form__input form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group my-2">
                <label asp-for="Email" class="control-label">Электронная почта*</label>
                <input asp-for="Email" type="email" class="login-form__input form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>


        </div>
        
        <div class="d-flex justify-content-between">
            <input type="submit" value="Отправить" class="btn btn-primary w-25 mt-3" />
        </div>
    </form>
</div>
@section Faq {
    <div id="faq">
    </div>
    <div id="faq-body">
        <p class="h5 fw-bold">Инструкция использования:</p>
        <p class="fw-bold">"Пользователь существует"</p>
        <p>Если пользователь существует, начните вводить его имя и выберите из списка.</p>
        <p class="fw-bold">"Пользователь не существует"</p>
        <p>Заполните все поля соответствующими заголовкам значениями.</p>
    </div>
}
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
        <script src="~/js/divisionMembersScript.js"></script>
    }
}

Views/Divisions/Index.cshtml
@model Event

@using DiplomService.ViewModels;
@using DiplomService.ViewModels.Divisions;
@using DiplomService.ViewModels.Measures;
@{
    ViewData["Title"] = "Подразделения";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    int eventId = 0;
    if (ViewBag.eventId != null)
    {
        eventId = ViewBag.eventId;
    }
}
<div class="intro" style="height:40vh">
    <div class="intro__column">
        <p class="intro__title">Заполните данные о подразделениях</p>
    </div>
</div>
<div class="container">
    <div class="navigation-block">
        <a asp-action="Edit" asp-controller="Events" asp-route-id="@Model.Id" class="cabinet-nav__item">Событие</a>
        <a asp-action="Index" asp-controller="Measures" asp-route-id="@Model.Id" class="cabinet-nav__item">Расписание</a>
        <a href="#" class="cabinet-nav__item">Подразделения</a>
    </div>
    <div class="circled-search__block">
        <input type="text" class="circled-search__input">
    </div>
        @{
        if (Model.Divisions.Count>0)
            foreach (var item in Model.Divisions)
            {
                <div class="my-3 justify-content-between item-block py-3 d-flex align-items-center">
                    <a asp-action="Edit" asp-controller="Divisions" asp-route-id="@item.Id" asp-route-eventId="@Model.Id" class="d-flex w-100 endHiden">
                        @if (item.PreviewImage != null)
                        {
                            string? mimeType = item.MimeType; // MIME-тип по умолчанию

                            if (mimeType != null)
                            {
                                <img src="data:@mimeType;base64,@Convert.ToBase64String(item.PreviewImage)" alt="Image" class="item-block__image">
                            }
                        }
                        else
                        {
                            <img src="/Images/camara.png" alt="Image" class="item-block__image">
                        }
                        <div class="ms-2">
                            <p class="item-block__title ">@item.Name</p>
                            <p>Участников: @item.DivisionMembers.Count(x=>!x.DivisionDirector)</p>
                        </div>
    
                    </a>
                    <div>
                        <form asp-action="Delete" method="post">
                            <input type="hidden" name="Id" value="@item.Id" />
                            <button type="submit" class="d-block login-form__submit w-100">Удалить</button>
                        </form>
                        <a asp-action="Members" asp-controller="Divisions" asp-route-id="@item.Id" class="d-block login-form__submit">Участники</a>
                        <a asp-action="Edit" asp-controller="Divisions" asp-route-id="@item.Id" class="d-block login-form__submit">Редактировать</a>
                    </div>
                </div>
            }
        
        else
        {
            <p class="align-content-center">Настройте подразделения проводимого события</p>
        }
        }
        <a href="/Divisions/Create/@Model.Id" class="btn btn-primary w-25 mt-3">
            Добавить подразделение
        </a>
        <div class="d-flex justify-content-between">
             <a href="/Measures/Index/@Model.Id" class="btn btn-primary my-3 w-25">Расписание</a>
             <a href="/Events/Publish/@Model.Id" class="btn btn-primary my-3 w-25">Опубликовать</a>
        </div>
</div>

@section Scripts{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/searchScript.js"></script>
    <script src="~/js/searchInputPopUp.js"></script>
}

Views/Divisions/Members.cshtml
@using DiplomService.Models.Users
@using DiplomService.Services
@model List<DivisionUsers>
@{
    ViewData["Title"] = "Участники подразделения";
    int? divisionId = ViewBag.divisionId;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="intro" style="height:40vh">
    <div class="intro__column">
        <p class="intro__title">Участники подразделения</p>
    </div>
</div>
<div class="container">
    @if (TempData["ErrorMessage"] != null)
    {
        <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
    }
    @if (Model is not null)
    {
        <p class="fw-bold h4 measureTitle">Участники</p>
        <div class="items-section">
            @foreach (var item in Model.Where(x => !x.DivisionDirector))
            {
                var user = item.User as MobileUser;
                if (user is null)
                    continue;
                <div class="item-block py-3 justify-content-between my-3 organization-user-item">
                    <div class="d-flex align-content-center multi-column-block">
                        @if (user.Image != null)
                        {
                            string? mimeType = ImageWorker.GetImageMimeType(user.Image); // MIME-тип по умолчанию

                            if (mimeType != null)
                            {
                                <img src="data:@mimeType;base64,@Convert.ToBase64String(user.Image)" alt="Image" class="item-block__image">
                            }
                        }
                        else
                        {
                            <img src="/Images/camara.png" alt="Image" class="item-block__image">
                        }
                        <div class="item-block__column">
                            <p class="item-block__title">@user.GetFullName()</p>
                            <p class="item-block__text">Дата рождения: @user.Birthday.ToShortDateString()</p>
                            <p class="item-block__text">Курс обучения: @user.Course</p>
                        </div>
                    </div>
                    <form asp-action="DeleteUserFromDivision" method="post" class="flex-row-block">
                        <input type="hidden" name="Id" value="@item.Id" />
                        <button type="submit" class="btn btn-primary d-block login-form__submit">Удалить из подразделения</button>
                    </form>
                </div>
            }
            <div class="w-100 d-flex justify-content-center">
                <a asp-controller="Divisions" asp-action="AddDivisionMember" asp-route-id="@divisionId" class="btn btn-primary mx-auto text-center">Добавить учаcтника</a>
            </div>
        </div>
        <p class="fw-bold h4 measureTitle">Ответственные пользователи</p>
        <div class="items-section">
            @foreach (var item in Model.Where(x => x.DivisionDirector))
            {
                <div class="item-block py-3 justify-content-between my-3 organization-user-item">
                    <div class="d-flex align-content-center multi-column-block">
                        @if (item.User.Image != null)
                        {
                            string? mimeType = ImageWorker.GetImageMimeType(item.User.Image); // MIME-тип по умолчанию

                            if (mimeType != null)
                            {
                                <img src="data:@mimeType;base64,@Convert.ToBase64String(item.User.Image)" alt="Image" class="item-block__image">
                            }
                        }
                        else
                        {
                            <img src="/Images/camara.png" alt="Image" class="item-block__image">
                        }
                        <div class="item-block__column">
                            <p class="item-block__title">@item.User.GetFullName()</p>
                            @if (item.User is OrganizationUsers)
                            {
                                <p class="item-block__text">Организация: @((item.User as OrganizationUsers)?.Organization.Name)</p>
                            }
                            else if (item.User is WebUser)
                            {
                                <p class="item-block__text">Образовательное учреждение: @((item.User as WebUser)?.WorkingPlace)</p>
                            }
                        </div>
                    </div>

                    <form asp-action="DeleteUserFromDivision" method="post" class="flex-row-block">
                        <input type="hidden" name="Id" value="@item.Id" />
                        <button type="submit" class="btn btn-primary d-block login-form__submit">Удалить из подразделения</button>
                    </form>
                </div>
            }
            <div class="w-100 d-flex justify-content-center">
                <a asp-controller="Divisions" asp-action="AddDivisionMember" asp-route-leader="true" asp-route-id="@divisionId" class="btn btn-primary mx-auto text-center">Добавить ответственного</a>
            </div>
        </div>


    }
   
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="~/js/searchScript.js"></script>
    <script src="~/js/searchInputPopUp.js"></script>
    <script src="~/js/slideItemScript.js"></script>
}